### ISSUE TITLE
myTemplate Example

### ISSUE THREAD

**Issue by guyver-dash** [mrabbani/VueTypeahead#10]
Hi there,

Can you give me an example of myTemplate methods. I've tried it but it doesn't work.

```
<vue-typeahead
                       v-model="value"
                       prefetch="https://twitter.github.io/typeahead.js/data/nfl.json"
                       :default-suggestion="false"
                       display-key='team'
                       :suggestion-template="myTemplate"
                       classes="form-control"
                       v-on:selected="done">

                </vue-typeahead>
```

Thanks for creating this.

**Comment by mrabbani** [comment]
Please, see [https://github.com/mrabbani/vuejs-autocomple-example/blob/master/resources/assets/js/app.js](https://github.com/mrabbani/vuejs-autocomple-example/blob/master/resources/assets/js/app.js)

**Comment by guyver-dash** [comment]
If I put it into a components it will give me an error. Vue is not defined. Why?

**Comment by guyver-dash** [comment]
It works now... I added import Vue from 'vue' from your VueTypeahead.vue file.

**Comment by frohikey** [comment]
Yeah, the same problem here.

``var res = Vue.compile(this.suggestionTemplate);`` fails because there's no Vue instance.

That workaround is quite ugly :(
I can't use npm package at all because npm/webpack is a part of the build on my server.

I ended up with creating local package and adding `` import Vue from 'vue'`` into ``VueTypeahead.vue``.
